### ISSUE TITLE
Network stack restart problem

### ISSUE THREAD

**Issue by laszlojakab** [baradi09/eazyctrl#5]
Hello Balint,

Could you please check discussion here:

https://github.com/laszlojakab/homeassistant-easycontrols/issues/46

and here:

https://github.com/home-assistant/core/issues/59170

Maybe the issue related to eazyctrl package.

Regards,
Laszlo

**Comment by baradi09** [comment]
It could easily be, indeed. Currently, the socket communication has a time-out window of 10 seconds, and 3 trials are done before the communication is considered to have failed. That would explain the experienced 30 second period in https://github.com/laszlojakab/homeassistant-easycontrols/issues/46#issuecomment-1003690743. I can lower the time-out window (and also add a better way to control it from outside). Would that solve the issue?

**Comment by laszlojakab** [comment]
I don't know let's try it out. In Home Assistant the sensors are updated in every 30 seconds by default so the mentioned 30 seconds could also be related to that value.

**Comment by laszlojakab** [comment]
Hello Balint, I've modified the eazyctrl package and introduced asynchronous methods with asyncio (and temporarly moved into the Home Assistant integration for testing). This solved the issue in Home Assistant (and as I see the performance is much better). If I create a PR with `AsyncEazyCommunicator` and `AsyncEazyController` classes can you release a new version of EazyCtrl package to pypi?
